### ISSUE TITLE
如果让GUVCView支持 Leopard 的 USB3摄像头需要改动哪些地方呢？

### ISSUE THREAD

**Issue by trickyMan** [danyu9394/li_guvcview_for_usb3#1]
Hi，DanYu:
     我注意到li_guvcview_for_usb3这个项目是对Leopard的摄像头做了一些支持，但因为并不是folk guvview并在其基础上修改，而是重新上传了一个新的项目，看不到你的历史commits. 所以无从追溯。
    我的问题是，Leopard需要对 guvcView做哪些特殊的改动才能够支持。

https://github.com/danyu9394/li_guvcview_for_usb3/blob/452cca2826f1c5f3f1e021dee257e39edb010d0e/gview_v4l2core/v4l2_xu_ctrls.c#L48
在这里我发现有一些Lepard的 Extension Unit的定义，我比较关心Software Trigger功能，但没有搜索到其他地方有用到，所以猜想你并没有集成Leopard的Software Trigger功能。

**Comment by danyu9394** [comment]
我主要在guvcview里面加了不同的camera id做不同的debayer，所以如果买了Leopard的bayer USB3 camera打开来就不是绿屏的（默认是YUV422格式的）。

v4l2_xu_ctrl这部分代码我下星期上传新的linux camera tool上面会有所有的functionality，有trigger的api，界面也先好了，测试能用的。关于兼容，不同的camera要看driver当初有没有写对应的代码支不支持具体哪个extension unit ctrl. 我camera tool的软件大概写好了，等我下周把readme什么补上去就commit。

v4l2_xu_ctrl这部分没有加在guvcview里是因为guvcview本身有点问题，分辨率大一点的相机经常会在上面跑时间长一点就死，显得好像是Leopard相机的问题，但应该是guvcview的bug。。。所以不想再在上面加东西了。而且guvcview代码实在太多了，debug起来累。

**Comment by trickyMan** [comment]
谢谢，我还没拿到摄像头，没法做实验，所以提前开始一些调研，只能够看代码，期待你的工具。对我很有帮助和参考意义。

**Comment by trickyMan** [comment]
我的邮箱是： philipjjj@hotmail.com ,你可以给我发一封邮件，可能我们会有工作上的交集，邮箱更方便讨论，BTW，我4.15降去硅谷调试采集设备。
